### PR TITLE
Added support for global handler + Added some missing http response codes

### PR DESCRIPTION
**Pull request by sumeetchhetri**
[Old PR](https://github.com/matt-42/lithium/pull/8)

### CODE REVIEW

**Comment by matt-42** [comment]
Hi @sumeetchhetri 
Files in single_headers/ are generated. Can you patch the files in https://github.com/matt-42/lithium/tree/master/libraries/http_server/http_server  instead ?

**Comment by sumeetchhetri** [comment]
> Hi @sumeetchhetri
> Files in single_headers/ are generated. Can you patch the files in https://github.com/matt-42/lithium/tree/master/libraries/http_server/http_server instead ?

Done

**Comment by matt-42** [comment]
Hi @sumeetchhetri , just checked your PR. You updated the right file but the tests are failling on travis. Please fix them before we can merge it into master.

**Comment by sumeetchhetri** [comment]
Fixed the failing builds, good to go.

**Comment by matt-42** [comment]
Looks great. Thanks. I'm merging it.

**Pull request merged**
